live_config_reload = true

[shell]
program = "/bin/zsh"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.8
blur = true
dynamic_title = true

[window.padding]
x = 20
y = 15

[keyboard]
bindings = [
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
    { key = "PageUp", mods = "Alt", action = "ScrollLineUp" },
    { key = "PageDown", mods = "Alt", action = "ScrollLineDown" },
]
